### ISSUE TITLE
MacOS compatibility

### ISSUE THREAD

**Issue by xjosh** [pbhenson/vSPC.py#25]
Git source compiled and installed just fine on MacOS. However, running fails like this:

`Traceback (most recent call last):
  File "/usr/local/bin/vSPCServer", line 222, in <module>
    sys.exit(main())
  File "/usr/local/bin/vSPCServer", line 180, in main
    handler = SysLogHandler(address="/dev/log")
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 762, in __init__
    self._connect_unixsocket(address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/logging/handlers.py", line 790, in _connect_unixsocket
    self.socket.connect(address)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 2] No such file or directory`

I realize MacOS compatibility wasn't promised but it sure would be nice. I'm not smart enough to know if this is easy or difficult to make work but figured I throw in a request. Happy to help test or otherwise contribute, just have near zero code skills.

**Comment by keeely** [comment]
It should be straightforward to get the service running in Docker which seems a better way to go for Mac compatibility.  In theory that doesn't need any coding skills :-).
